# Missing values


The only missing values we encountered in our datasets are in CAL FIRE Table 18 (Dollar Damage by Cause, by County).  Specifically, those tables do not include damage costs for 6 (of 58) counties i.e. the so-called "Contract Counties" (Kern, Los Angeles, Marin, Orange, Santa Barbara, and Ventura). According to CAL FIRE, "The State contracts with six counties to provide protection of SRA within their boundaries."  While these counties apparently provided certain information on wildfire incidents (e.g. the data for the Contract Counties is provided in Tables 5 and 6), the damage costs (Table 18) were not provided for any of the years we examined in our analysis.  We determined this information by visually comparing a list of California counties (available online) with the list of counties in the CAL FIRE dataset for Table 18. 

Some datasets like the Tables 5 and 6 from CAL FIRE did not contain values for all variables (e.g. Counties or Fatalities) and all incidents or years, however we could not conclude that they were missing because the observations were not recorded.  For example, over the 5 year period not all counties had reported wildfire incidents with sizes over 300 acres during each year (typically 52-53 counties of 58 in total would have recorded information each year), nor all fire incidents would have recorded fatalities (most of them did not have any at all).  In all of those cases it appeared that the information that was recorded was only for the events that occurred.

