--- 
title: "California Fires"
author: "Abhishek Sinha, Tomislav Galjanić"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


The large and devastating wildfires in the United States (especially in the West) and globally have become a common story across the news channels in recent years. According to the California Air Resources Board (CARB), the state agency that oversees climate change programs and pollution control efforts, “climate change, primarily caused by the burning of fossil fuels, is increasing the frequency and severity of wildfires not only in California but also all over the world. Since 1950, the area burned by California wildfires each year has been increasing, as spring and summer temperatures have warmed and spring snowmelt has occurred earlier.”

In this project, our goal is to investigate the magnitude of changes in frequency and size of wildfires in California and the impacts in recent years that the wildfires have had on the economy, businesses, and people in the State of California. Our analysis focuses initially on identifying trends in wildfires in the last 35 years and then we proceed to look at their economic and human impact across the state and different regions in the period from 2015-2019. As some of the largest wildfires in California in recent years have been caused by electrical infrastructure (typically sparks from distribution and transmission lines), in the last part of our analysis we investigate the impact of wildfires on the wildfire prevention activities of the electric utility companies in California and costs associated with those activities.  We specifically look at the level of capital and O&M spending for the fire prevention activities of the Pacific Gas & Electric Company, the power utility responsible for many large wildfires in northern California in the past 5 years, which had to make large financial settlement payouts to the fire victims and make significant investment in equipment and activities aimed at reducing the risk of future fires from utility equipment.
